"""Base abstractions for LLM providers supporting chat completions and tool calls."""

from abc import ABC, abstractmethod
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ToolCallRequest(BaseModel):
    """Normalized representation of an LLM tool-call request."""

    model_config = ConfigDict(arbitrary_types_allowed=True)

    id: str = Field(..., description="Unique identifier for the tool call")
    name: str = Field(..., description="Target tool function name")
    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Parsed arguments dictionary for the tool function",
    )
    thought_signature: bytes | str | None = Field(
        default=None,
        description="Opaque thought signature from reasoning models (e.g. Gemini 3)",
    )
    raw_part: Any = Field(
        default=None,
        description="Native SDK Part object preserved for provider continuity across turns",
    )
    thought_parts: list[Any] = Field(
        default_factory=list,
        description="Preceding or associated thought parts from reasoning models",
    )



class LLMMessage(BaseModel):
    """Normalized conversation message across all supported roles."""

    role: Literal["system", "user", "assistant", "tool"] = Field(
        ...,
        description="Message sender role",
    )
    content: str | None = Field(
        default=None,
        description="Text content of the message",
    )
    name: str | None = Field(
        default=None,
        description="Optional participant or tool name",
    )
    tool_call_id: str | None = Field(
        default=None,
        description="Required when role='tool' to reference the originating tool call",
    )
    tool_calls: list[ToolCallRequest] | None = Field(
        default=None,
        description="Tool calls initiated by the assistant",
    )


class LLMResponse(BaseModel):
    """Normalized output from an LLM provider generation step."""

    content: str | None = Field(
        default=None,
        description="Text response generated by the model",
    )
    tool_calls: list[ToolCallRequest] = Field(
        default_factory=list,
        description="List of tool calls requested by the model",
    )
    finish_reason: str = Field(
        default="stop",
        description="Reason model stopped generating (e.g. 'stop', 'tool_calls', 'length')",
    )
    usage: dict[str, int] = Field(
        default_factory=dict,
        description="Token usage accounting (e.g. prompt_tokens, completion_tokens)",
    )

    @property
    def has_tool_calls(self) -> bool:
        """True if model requested one or more tool calls."""
        return len(self.tool_calls) > 0


class LLMProvider(ABC):
    """Abstract base class for LLM communication providers."""

    @abstractmethod
    async def generate_response(
        self,
        messages: list[LLMMessage],
        tools: list[dict[str, Any]] | None = None,
    ) -> LLMResponse:
        """Send messages to the model and return structured response or tool calls."""
        pass
