"""create sandboxes and execution_jobs tables

Revision ID: 3190bf3b73be
Revises:
Create Date: 2026-09-09 20:02:05.603874

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3190bf3b73be'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandboxes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('resource_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxes_created_at'), 'sandboxes', ['created_at'], unique=False)
    op.create_index(op.f('ix_sandboxes_expires_at'), 'sandboxes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sandboxes_status'), 'sandboxes', ['status'], unique=False)
    op.create_table('execution_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sandbox_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('stdout_truncated', sa.Boolean(), nullable=False),
    sa.Column('stderr_truncated', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_jobs_sandbox_id'), 'execution_jobs', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_status'), 'execution_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_execution_jobs_submitted_at'), 'execution_jobs', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_jobs_submitted_at'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_status'), table_name='execution_jobs')
    op.drop_index(op.f('ix_execution_jobs_sandbox_id'), table_name='execution_jobs')
    op.drop_table('execution_jobs')
    op.drop_index(op.f('ix_sandboxes_status'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_expires_at'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_created_at'), table_name='sandboxes')
    op.drop_table('sandboxes')
    # ### end Alembic commands ###
