"""Request and response schemas for AI Agent REST APIs."""

from pydantic import BaseModel, Field, field_validator


class AgentRunRequest(BaseModel):
    """Request payload for initiating an AI agent execution run."""

    prompt: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="Natural language instruction or question for the AI agent",
        examples=["Calculate factorial of 20 using Python and explain the result."],
    )

    @field_validator("prompt")
    @classmethod
    def validate_prompt(cls, v: str) -> str:
        """Ensure prompt is not empty or composed solely of whitespace."""
        clean = v.strip()
        if not clean:
            raise ValueError("Prompt cannot be empty or solely whitespace.")
        return clean


class AgentRunResponse(BaseModel):
    """Structured response returned by the AI agent execution endpoint."""

    response: str = Field(
        ...,
        description="Final natural-language response generated by the agent",
    )
    tools_used: bool = Field(
        ...,
        description="True if one or more sandbox tools were executed during reasoning",
    )
    iterations: int = Field(
        ...,
        ge=1,
        description="Total agent reasoning iterations completed",
    )
    tool_calls_count: int = Field(
        default=0,
        ge=0,
        description="Total tool calls executed across all iterations",
    )
    executed_tools: list[str] = Field(
        default_factory=list,
        description="Names of tools executed during the run in chronological order",
    )
